version: '3.8'

services:
  backend:
    build: ./node-express-backend
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=development
      - PORT=5000
      - MONGODB_URI=mongodb+srv://telepharma:54JOsb1qKxeaeBKr@telepharma.dqzjtv7.mongodb.net/telemedicine
      - JWT_SECRET=telemedicine-jwt-secret-key-2024
      - FIREBASE_PROJECT_ID=telemedicine-31088
      - FIREBASE_PRIVATE_KEY_ID=4c23a1483387d2b41d2857094f21cec23e7ab8da
      - FIREBASE_PRIVATE_KEY=-----BEGIN PRIVATE KEY-----\nMIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQDsn3Shwt3CNJxI\nccnm7rayWsp06aWJmIqdwqC4A7nDHoF/B35aIXPE+tOPumE9SMsgsi7vaj5xlO5N\nyRzBACmnN275QUEUmXdG5zKzfydpMRfMeE73Tj34tXVO6lnwtzpYurF8GtonETco\nLZEr7vpga46jIvq/dj3JFuS7aDg2DOhgN3eftYolibp3wDcYQs0BEGZkBlXg1Kv2\nbZer1pSyN4LJX88nJE1rw9bA+vm6hd2NKoJauW4ppfRo4e2EpoxFw2AoU3zn0gq5\nKWoVhb7Q670gdPQojPu/e2KVB14XwzKer/XzY30igIZou2w+esOdInTFK+Y1qdK/\nokGSuVAPAgMBAAECggEABAgouxoW03I4PxqQdHRl1yUpfpN90OaxM5EqhU6SJQtJ\nU2PjzCv2WbyYy6hDDU6TueNlxFbJm8xyjdwntsXGox6t/LMXC+XpIxambDbC8g2c\ny7M5f6JGkQ0HSi7ZFUgLlCtEm4pAZFqfpEbrSqKmtoTh22rDRG1PdGeejyKH+3fC\nPz1J0L0DR+sEiOiS1j2hx7/586zbql3sR0I5CQbtILWLLx4oyupRsKO7Ims71i1+\nCXE4r8BLq+phyp3khanTQ8gHlkezVJEJXb5c0mA3UoV1QdAeAGvK3IrK5Q9xXimT\nFiMS4n1nWP7qukdmRsu6ALWgoAAW8QZz0XrsFvT8BQKBgQD8MsBAJFIvdfsblswB\nfNa0nvUk4l/AuyyCPb0GSJ6BvA/E6WmcgBsLlbKRJPykHDDk8lhK4sRK8IEKch+V\n9T+kbOHgZoWy0hX1+zNriOb5IcAP+WLsZVlKo56oz6PEJsEQvsuIst/E0ea6ARBm\ng9rnkdAYzthAz4VEV3j4L/yVGwKBgQDwMJkn11sBV1fdRhKkmuzQA57vVSDx/IJ8\nwkWgKZ48oWjB9tqAoAqbx3uIpxLLILiNeEKh+6Qd1Vc7ZIa0vHYHjO7Bu2klyoye\nkd7Bssf34XjMy5tYilO+moI7w8xz0QTHxySKyY+b+uS74JEPFVYz7eEmMovqpq1c\nYLOTRtgEHQKBgDe3wq+pFpsztqGWxEWD3i+TeteGR99duuyfVTahLpu8/8LiSpnv\n14nMreHRSRu8urSqMgWBahqgXfH/2qiXwVLDV3frTph+P6nTsL2ORnE+Gp+s2kUd\n8wdBdNkY3raEVV0suezej/983Du15nivotpMZaxFbpOLBYdex/QVLfmHAoGBAJyI\nn5fWgwnJuYqMu2OpUAJ1CaSijzkFvqi+F5A871JGQzZ9wYMoSiGiDQFPGTFmnsAc\nCxj0Hc4Plq0vY5bwZ9+d2pBJqkolyiUhndIQyL/kosydOR2n8NH8cjmu7lTgeMQW\nJduJZt1Z0q4auY7h8e8f7abuND915u+YWg/2kJuFAoGBAPBhrYIregjzxCr/qsnV\ndYKtRZ+57Q23Eip6vYoTfd968VtaGyePu/uf8vSWmQKU7x2/4yX6Wreyf2kwob9N\nZLPZNCjXPa7+x6UaGxvdMQ/9jVZQBRuXjYGaSIUUH+tcFlwhIH7UETwC0K3gxLKc\ngvpPiNqeiiuCJa64+Zz23h7x\n-----END PRIVATE KEY-----\n
      - FIREBASE_CLIENT_EMAIL=firebase-adminsdk-fbsvc@telemedicine-31088.iam.gserviceaccount.com
      - FIREBASE_CLIENT_ID=114521692844910220312
    volumes:
      - ./node-express-backend:/app
      - /app/node_modules
    restart: unless-stopped

  frontend:
    build: ./nextjs-frontend
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:5000
      - NEXT_PUBLIC_FIREBASE_API_KEY=AIzaSyDwdp8YC0hg-3hrxRkrcXjGCx517Fq1nW0
      - NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN=telemedicine-31088.firebaseapp.com
      - NEXT_PUBLIC_FIREBASE_PROJECT_ID=telemedicine-31088
      - NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET=telemedicine-31088.firebasestorage.app
      - NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID=792144509907
      - NEXT_PUBLIC_FIREBASE_APP_ID=1:792144509907:web:2632bfae6ae6c50b078d26
      - NEXT_PUBLIC_FIREBASE_MEASUREMENT_ID=G-278E0JEE4L
      - NEXT_PUBLIC_FIREBASE_VAPID_KEY=BFgRm0lhkXu4ODQ9dXuKqdOMSRdV2tT_Yi8CiuedaJAEE28k47Xr58zcXdoEojQKFqDHgPAHTsIs3fvZpI0QJ1w
    volumes:
      - ./nextjs-frontend:/app
      - /app/node_modules
      - /app/.next
    depends_on:
      - backend
    restart: unless-stopped